image:
  repository: andriiuni 
  name: spam2000
  tag: 1.1394.355

app:
  name: spam2000
  namespace: app 

service:
  type: ClusterIP
  ports:
    port: 80
    targetPort: 3000

ingress:
  spec:
    rules:
      host: spam2000.uni.local