apiVersion: v2
name: vmstack
description: "Umbrella app for VictoriaMetrics single + Grafana + exporters (prometheus-node-exporter, kube-state-metrics)"
type: application
version: 0.1.0

dependencies:
  - name: victoria-metrics-single
    version: 0.25.5
    repository: https://victoriametrics.github.io/helm-charts/

  # - name: victoria-metrics-agent
    # version: 0.26.5
    # repository: https://victoriametrics.github.io/helm-charts/

  - name: kube-state-metrics
    version: 6.4.2
    repository: https://prometheus-community.github.io/helm-charts

  - name: prometheus-node-exporter
    version: 4.49.2
    repository: https://prometheus-community.github.io/helm-charts

  - name: grafana
    version: 10.2.0
    repository: https://grafana.github.io/helm-charts
