apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam2000
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alakaganaguathoork/uni-test-task.git
    targetRevision: 0.1.0
    path: helm/charts/spam2000
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.minikube-mine.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true