apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spam2000
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alakaganaguathoork/uni-test-task.git
    targetRevision: HEAD
    path: helm/charts/spam2000
    # helm:
      # valueFiles:
        # - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true