apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vm-stack
  namespace: argocd
  # finalizers:
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alakaganaguathoork/uni-test-task.git
    path: helm/charts/vmstack
    targetRevision: HEAD
    # helm:
      # valueFiles:
        # - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true