apiVersion: v2
name: vmstack
description: "Umbrella chart for ArgoCD"
type: application
version: 0.1.0

dependencies:
  - name: argo-cd
    version: 9.1.4
    repository: https://argoproj.github.io/argo-helm
    alias: argocd